# Generated by Django 2.0.2 on 2020-03-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(verbose_name='成绩')),
            ],
            options={
                'verbose_name_plural': '成绩信息',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False, verbose_name='课程号')),
                ('lesson_name', models.CharField(max_length=20, verbose_name='课程名')),
                ('lesson_local', models.CharField(default=None, max_length=30)),
                ('lesson_time', models.CharField(default=None, max_length=30)),
            ],
            options={
                'verbose_name_plural': '课程表单',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='学生序号')),
                ('student_study_id', models.IntegerField(verbose_name='学号')),
                ('student_name', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('student_sex', models.CharField(default='男', max_length=3, verbose_name='性别')),
                ('student_id_card', models.IntegerField(verbose_name='身份证')),
                ('student_go_school_year', models.IntegerField(verbose_name='入学年份')),
                ('student_major', models.CharField(max_length=20, verbose_name='专业')),
                ('student_id_home', models.CharField(max_length=20, verbose_name='户籍')),
                ('student_study_style', models.CharField(max_length=20, verbose_name='就读状态')),
                ('student_passwd', models.CharField(default=None, max_length=6, verbose_name='登陆密码')),
            ],
            options={
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False, verbose_name='老师编号')),
                ('teacher_name', models.CharField(max_length=20, verbose_name='老师姓名')),
                ('lesson', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Student.Lesson')),
            ],
            options={
                'verbose_name_plural': '老师信息',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ManyToManyField(to='Student.Student'),
        ),
        migrations.AddField(
            model_name='grades',
            name='lesson_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Student.Lesson', verbose_name='课程名称'),
        ),
        migrations.AddField(
            model_name='grades',
            name='student_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Student.Student', verbose_name='学生姓名'),
        ),
    ]
