# Generated by Django 2.0.2 on 2020-03-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_addr',
            field=models.CharField(default=None, max_length=100, verbose_name='通讯地址'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.CharField(default=None, max_length=20, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_tel',
            field=models.IntegerField(default=22, verbose_name='手机号码'),
        ),
    ]
