# Generated by Django 2.0.2 on 2020-03-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20200321_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_short',
            field=models.CharField(default=None, max_length=500, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_tel',
            field=models.IntegerField(default=50, verbose_name='手机号码'),
        ),
    ]
