# Generated by Django 2.0.2 on 2020-03-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20200321_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_tel',
            field=models.IntegerField(default=50, max_length=50, verbose_name='手机号码'),
        ),
    ]
