# Generated by Django 2.0.2 on 2020-03-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_auto_20200322_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_data',
            field=models.CharField(default=None, max_length=20, verbose_name='年份'),
        ),
    ]
