# Generated by Django 2.0.2 on 2020-03-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_lesson_lesson_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('news_body', models.TextField(max_length=5000, verbose_name='新闻内容')),
            ],
            options={
                'verbose_name_plural': '新闻信息',
            },
        ),
    ]
