# Generated by Django 2.0.2 on 2020-03-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_brief',
            field=models.CharField(default=333, max_length=200, verbose_name='新闻简略'),
        ),
    ]
