# Generated by Django 2.0.2 on 2020-03-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_news_news_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_num',
            field=models.IntegerField(default=121, verbose_name='剩余可选人数'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ManyToManyField(default=None, to='Student.Student'),
        ),
    ]
