# Generated by Django 2.0.2 on 2020-03-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_auto_20200323_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=50, verbose_name='考试名称')),
                ('exam_time', models.CharField(max_length=100, verbose_name='考试时间')),
                ('student', models.ManyToManyField(default=None, to='Student.Student')),
            ],
            options={
                'verbose_name_plural': '全国考试列表',
            },
        ),
    ]
