# Generated by Django 2.0.2 on 2020-04-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id_card',
            field=models.IntegerField(max_length=255, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_tel',
            field=models.IntegerField(default=50, max_length=255, verbose_name='手机号码'),
        ),
    ]
