# Generated by Django 2.0.2 on 2020-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_auto_20200423_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id_card',
            field=models.BigIntegerField(verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_tel',
            field=models.BigIntegerField(default=50, verbose_name='手机号码'),
        ),
    ]
